version: "3.2"

services:
  service-account:
    build:
      context: .
      dockerfile: apps/service-account/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - consul
    image: "service-account:latest"
    restart: always
    environment:
      - CONSUL_HOST=localhost
      - NATS_HOST=localhost
      - MQTT_HOST=localhost
      - MQTT_USER=""
      - MQTT_PASS=""
    ports:
      - 50054:50054
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-access:
    build:
      context: .
      dockerfile: apps/service-access/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - consul
    image: "service-access:latest"
    restart: always
    environment:
      - CONSUL_HOST=localhost
      - NATS_HOST=localhost
      - MQTT_HOST=localhost
      - MQTT_USER=""
      - MQTT_PASS=""
    ports:
      - 50089:50089
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-billing:
    build:
      context: .
      dockerfile: apps/service-billing/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - consul
    image: "service-billing:latest"
    restart: always
    environment:
      - CONSUL_HOST=localhost
      - NATS_HOST=localhost
      - MQTT_HOST=localhost
      - MQTT_USER=""
      - MQTT_PASS=""
    ports:
      - 50067:50067
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-notification:
    build:
      context: .
      dockerfile: apps/service-notification/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - consul
    image: "service-notification:latest"
    restart: always
    environment:
      - CONSUL_HOST=localhost
      - NATS_HOST=localhost
      - MQTT_HOST=localhost
      - MQTT_USER=""
      - MQTT_PASS=""
    ports:
      - 50044:50044
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-role:
    build:
      context: .
      dockerfile: apps/service-role/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - consul
    image: "service-role:latest"
    restart: always
    environment:
      - CONSUL_HOST=localhost
      - NATS_HOST=localhost
      - MQTT_HOST=localhost
      - MQTT_USER=""
      - MQTT_PASS=""
    ports:
      - 50052:50052
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-tenant:
    build:
      context: .
      dockerfile: apps/service-tenant/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - consul
    image: "service-tenant:latest"
    restart: always
    environment:
      - CONSUL_HOST=localhost
      - NATS_HOST=localhost
      - MQTT_HOST=localhost
      - MQTT_USER=""
      - MQTT_PASS=""
    ports:
      - 50053:50053
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  api-admin:
    build:
      context: .
      dockerfile: apps/api-admin/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - consul
    image: "api-admin:latest"
    restart: always
    environment:
      - CONSUL_HOST=localhost
      - NATS_HOST=localhost
      - MQTT_HOST=localhost
      - MQTT_USER=""
      - MQTT_PASS=""
    ports:
      - 50020:50020
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  consul:
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    image: consul
    command: ["agent", "-server", "-bootstrap", "-ui", "-client", "0.0.0.0"]
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"

  eventstore:
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    image: eventstore/eventstore
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"

  mqtt:
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    image: eclipse-mosquitto
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"

  memcached:
    container_name: memcached
    image: launcher.gcr.io/google/memcached1
    ports:
      - "11211:11211"
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"

  nats:
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    image: nats
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeit
    restart: always
    expose:
      - 27017

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379
